### ISSUE TITLE
typos in platform detection macros

### ISSUE THREAD

**Issue by bedax** [qwercik/uptime#1]
Hello, there's a typo on line 6, it says `linux` instead of `__linux__`. Lines 31 and 80 have similar typos too.

Otherwise, thank you very much for this library! Great work

**Comment by qwercik** [comment]
Thank you for your feedback! I fixed this typo (and some other stupid mistakes). I hope everything will be OK ;)

**Comment by iongrove** [comment]
Brilliant, looks good! Thanks again :+1:

**Comment by bedax** [comment]
Brilliant, looks good! Thanks again :+1:
